### ISSUE TITLE
how to convert uncrypted .ini to crypted .ini

### ISSUE THREAD

**Issue by asdffdsazqqq** [netinvent/configparser_crypt#2]
hello, thanks,

please, if i have an existing .ini file, how can i crypt it?
i need a converter.
i read the docs and source code, could not figure it out.

thanks much,
david

**Comment by deajan** [comment]
Easy one, use `read` function to read original ini file then use `write_encrypted` to create New version.
Keep in mind that secure deletion of source file is out of scope.

**Comment by asdffdsazqqq** [comment]
yes, that was easy one and a quick reply. 

fwiw, to me, was not clear that configparser_crypt.read() reads a non-decrypted .ini file

thanks much,
david

**Comment by deajan** [comment]
Improved the documentation a bit ;)
Feel free to open new issues if you need help

**Comment by asdffdsazqqq** [comment]
thanks much,

the updated docs are great

overall, very easy to switch from python config to your configparser_crypt

tho i ran into some confusing problems with interpolation errors
that `%` needs to changed to %%`

**Comment by deajan** [comment]
Very strange, since the class actually inherits from the original ConfigParser class, and just adds a couple of new functions for cryptography.
Could you perhaps come up with an example of the interpolation problems you're talking about ?
I'd be happy to see what the problem could be and how I could resolve it.

PS: If the comment on [stackoverflow ](https://stackoverflow.com/a/70633543/2635443) was you, I'd be delighted if you would upvote my implementation if it fits your needs.

**Comment by asdffdsazqqq** [comment]
deajan, yes, that was me at stackoverflow,
fwiw, when i first posted there, i tried to upvote but cannot yet.
i just tried again, still cannot upvote, sorry about that
"Thanks for the feedback! You need at least 15 [reputation](https://stackoverflow.com/help/whats-reputation) to cast a vote, but your feedback has been recorded."

--------------------------

here is the output of my python program,  tried to read `RclonePassword` from the .ini file
the trouble text from .ini is `RclonePassword=+oy%#"An2EBKc3Gb@`
if i change that to `RclonePassword=+oy%%#"An2EBKc3Gb@`, then no errors

and here is the output from python.
```
DoEnd: ERROR: GetKey - Traceback (most recent call last):
  File "C:\data\rclone\common.py", line 167, in GetKey
    Value = Common.config[Section][TheKey]
  File "D:\Program Files\Python39\lib\configparser.py", line 1255, in __getitem__
    return self._parser.get(self._name, key)
  File "D:\Program Files\Python39\lib\configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "D:\Program Files\Python39\lib\configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "D:\Program Files\Python39\lib\configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%#"An2EBKc3Gb@'
```

**Comment by deajan** [comment]
Okay, that's actually a ConfigParser error that ConfigParserCrypt just inherits.
By default, ConfigParser uses interpolation.

You can disable that behavior in order to use 'raw' chars by using
```
config_file = ConfigParserCrypt(interpolation=None)
```
With the above, the '%' char will not be interpreted.
Just added an interpolation test in https://github.com/netinvent/configparser_crypt/commit/e46240f8dbc209c64c6ed7f2f33854b9b403ec60

Oh, and don't worry for stackoverflow. No problem ;)

**Comment by asdffdsazqqq** [comment]
good, that  is not an issue with your code.

i will have to educate myself about interpolation.

i am good now,
david
